/*
 * FILo <> Facebook Image Loader jQuery Plugin v1.1
 * http://www.berlinpix.com/filo
 *
 * Copyright 2014, BerlinPix.com
 * licensed under the LGPL license.
 *
 * Date: 2014-01-24
 */
(function(c){function s(a,b,c,e){if("function"==typeof e.before){var d=jQuery.Event("FILo Before Event");e.before(d)}d=a.filo.root_path;d=void 0==e.filo_loaderGraphic?d+a.filo.filo_loaderGraphicDefault:e.filo_loaderGraphic;if(null==a(".filo_loader")||0==a(".filo_loader").length){var g=new Image;g.onload=function(){a(g).css("marginTop",-1*(this.height/2));a(g).css("marginLeft",-1*(this.width/2));a("#"+String(b)).append(g)};g.setAttribute("class","filo_loader");g.src=d}var i=[];a.each(a("#"+String(b)).find(".excluded"),
function(b,c){i.push(a(c).attr("id"))});var f=[];a.each(a("#"+b).find(".album"),function(b,c){f.push(a(c).attr("id"))});if(void 0!=e.albums&&0<e.albums.length)for(d=0;d<e.albums.length;d++)f.push(decodeURI(e.albums[d]));if(void 0!=e.excluded&&0<e.excluded.length)for(d=0;d<e.excluded.length;d++)i.push(decodeURI(e.excluded[d]));var d="https://graph.facebook.com/fql?q=",j="",j=0<parseInt(c)?JSON.stringify({albums:"SELECT aid, name FROM album WHERE owner = "+c}):JSON.stringify({page_id:"SELECT page_id FROM page WHERE username = '"+
c+"'",albums:"SELECT aid, name FROM album WHERE owner IN (SELECT page_id FROM #page_id)"}),d=d+encodeURIComponent(j);a.browser.msie?a.ajax({url:d,dataType:"jsonp"}).success(function(h){h=h.data;v(a,b,c,1<h.length?h[1].fql_result_set:h[0].fql_result_set,f,i,e)}):a.getJSON(d,function(h){h=h.data;h=1<h.length?h[1].fql_result_set:h[0].fql_result_set;0>=h.length&&(a(".filo_loader").remove(),alert("There are no albums, please check your Facebook-ID"));v(a,b,c,h,f,i,e)}).error(function(){a(".filo_loader").remove();
alert("Error while loading, please check your Facebook-ID or write me: info@berlinpix.com")})}function v(a,b,c,e,d,g,i){a.filo.toLoad[b]=0;a.filo.isLoaded[b]=0;for(album in e)e[album].name=e[album].name.replace(/[\/]/g,":");var f="";0<d.length?a.each(e,function(e,h){if(w(h.name,d)){a.filo.toLoad[b]+=1;var g=a.filo.maxCountDefault;void 0!=a("#"+b+" #"+h.name).attr("maxCount")?g=parseInt(a("#"+b+" #"+h.name).attr("maxCount")):void 0!=a("#"+b+" #"+h.name.toLowerCase()).attr("maxCount")?g=parseInt(a("#"+
b+" #"+h.name.toLowerCase()).attr("maxCount")):void 0!=i&&void 0!=i.maxCount&&(g=i.maxCount);f="all"==g?JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+h.aid+"'"}):JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+h.aid+"' LIMIT "+g});var p="https://graph.facebook.com/fql?q="+encodeURIComponent(f);a("#"+b+" #"+h.name).remove();a("#"+b+" #"+h.name.toLowerCase()).remove();var l=a('<div class="album" id="'+h.name+'"></div>').append('<div class="title">'+h.name.replace(/[:]/g,
"/")+'</div><div class="thumbs"></div>');a(l).hide();a("#"+b).append(l);a.browser.msie?a.ajax({url:p,dataType:"jsonp"}).success(function(e){r(1,a,c,b,e.data[0].fql_result_set,l,g,i)}):a.getJSON(p,function(e){r(1,a,c,b,e.data[0].fql_result_set,l,g,i)})}}):a.each(e,function(e,h){if(!w(h.name,g)){a.filo.toLoad[b]+=1;var d=a.filo.maxCountDefault;void 0!=i&&void 0!=i.maxCount?d=i.maxCount:void 0!=a("#"+h.name).attr("maxCount")&&(d=parseInt(a("#"+h.name).attr("maxCount")));f="all"==d?JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+
h.aid+"'"}):JSON.stringify({photos:"SELECT src, src_big FROM photo WHERE aid = '"+h.aid+"' LIMIT "+d});var p="https://graph.facebook.com/fql?q="+encodeURIComponent(f),l=a('<div class="album" id="'+h.name+'"></div>').append('<div class="title">'+h.name.replace(/[:]/g,"/")+'</div><div class="thumbs"></div>').hide();a("#"+b).append(l);a.browser.msie?a.ajax({url:p,dataType:"jsonp"}).success(function(e){r(1,a,c,b,e.data[0].fql_result_set,l,d,i)}):a.getJSON(p,function(e){r(1,a,c,b,e.data[0].fql_result_set,
l,d,i)})}})}function r(a,b,c,e,d,g,i,f){var j=1==a?1:26*(a-1),h=[],a=d,k=b.filo.root_path;if(void 0!=f.order&&"reverse"==f.order)a.reverse();else if(void 0!=f.order&&"random"==f.order){for(var p=[],l=[];p.length<i&&p.length<a.length;){var q=Math.floor(Math.random()*a.length);void 0==l[q]&&(p.push(a[q]),l[q]=!0)}a=p}b.each(a,function(a,e){h[j-1]=e.src_big;var l=1==j?" first":"",p=j==i?" last":"",q=new Image;q.setAttribute("class","picture filo_picture");q.setAttribute("id",j-1);var r=0;q.onerror=function(){2>
r?(console.log("load picture again: "+e.src),q.src=e.src,r++):(q.onerror=null,q.src=b.filo.root_path+b.filo.defaultImage)};q.src=e.src;l=b('<div class="thumb thumb_'+j+l+p+'"><div class="inner"><a href="'+e.src_big+'"></a></div></div>');b(l).find("a").append(q);b(g).find(".thumbs").append(l);b(g).find(".filo_picture").unbind("click");b(g).find(".filo_picture").click(function(a){a.preventDefault();if(void 0!=f.href)return void 0!=f.method&&"post"==f.method.toLowerCase()?(a=!0==f.newWindow?'target="_blank"':
"",b("body").append('<form id="filo_forward" '+a+' method="POST" action="'+f.href+'"><input name="profile" value="'+c+'" /><input name="album" value="'+b(g).attr("id")+'" /></form>'),b("#filo_forward").trigger("submit").remove()):f.newWindow?window.open(f.href+"?profile="+c+"&album="+b(g).attr("id")):document.location=f.href+"?profile="+c+"&album="+b(g).attr("id"),!1;if(1>b(".filo_overlay").length){b.filo.closeButton=k+b.filo.closeButtons.black;void 0!=f.closeButton&&(b.filo.closeButton=void 0!=b.filo.closeButtons[f.closeButton]?
k+b.filo.closeButtons[f.closeButton]:f.closeButton);var e=900;b.each(b("body *"),function(a,c){"auto"!=b(c).css("zIndex")&&(e=Math.max(e,parseInt(b(c).css("zIndex"))))});var a=void 0!=f.overlay?"background: "+f.overlay+"; ":"background: "+b.filo.overlayDefault+";",d=void 0!=f.overlayOpacity?" opacity: "+f.overlayOpacity+";":" opacity: "+b.filo.overlayOpacityDefault+";";b("body").append('<div class="filo_overlay" style="z-index:'+(e+1)+';" ><div class="filo_overlay_background" style="'+a+d+'"></div><div class="filo_overlay_container"><div class="filo_overlay_container_left"></div><div class="filo_overlay_container_right"></div><div class="picture_counter"></div></div></div>');
var i=new Image;i.onload=function(){b(".filo_overlay_container").append(i);var a=0<b(".filo_overlay_container").css("border-width")?b(".filo_overlay_container").css("border-width"):17;b(this).css("right",-1*(this.width/2+a));b(this).css("top",-1*(this.height/2+a));i.setAttribute("class","filo_overlay_container_close");b(".filo_overlay_container_close").click(function(){b(".filo_overlay").remove()})};i.src=b.filo.closeButton;t(b,b(this).attr("id"),h,b(g).attr("id"),f);b(".filo_overlay_background").click(function(a){"filo_overlay_background"==
b(a.target).attr("class")&&b(".filo_overlay").remove()});b(".filo_overlay_container_left").click(function(){var a=parseInt(b(".filo_full_picture").attr("id"));0<a&&t(b,a-1,h,b(g).attr("id"),f)});b(".filo_overlay_container_right").click(function(){var a=parseInt(b(".filo_full_picture").attr("id"));a<h.length-1&&t(b,a+1,h,b(g).attr("id"),f)});b(".filo_overlay_container_left").mouseenter(function(){b(this).css("backgroundColor","none").css("background-image","url('"+k+"/img/left_white.png')").css("background-repeat",
"no-repeat").css("background-position","left center")}).mouseout(function(){b(this).css("background-image","")});b(".filo_overlay_container_right").mouseenter(function(){b(this).css("backgroundColor","none").css("background-image","url('"+k+"/img/right_white.png')").css("background-repeat","no-repeat").css("background-position","right center")}).mouseout(function(){b(this).css("background-image","")})}});if(j>=i)return b(g).append('<div class="clear"></div>'),!1;j++;j==d.length&&b(g).append('<div class="clear"></div>')});
b.filo.isLoaded[e]+=1;b(g).fadeIn("slow");b.filo.isLoaded[e]==b.filo.toLoad[e]&&(b("#"+e+" .album").last().attr("class",b("#"+e+" .album").last().attr("class")+" last"),b("#"+e).append('<div class="clear"></div>'),b("#"+e+" .add").remove(),b("#"+e+" .excluded").remove(),b("#"+e+" .filo_loader").remove(),"function"==typeof f.load&&(e=jQuery.Event("FILo Load Event"),f.load(e)))}function t(a,b,c,e,d){a(".filo_overlay_container_left").show();a(".filo_overlay_container_right").show();0==b&&a(".filo_overlay_container_left").hide();
b==c.length-1&&a(".filo_overlay_container_right").hide();var g=parseInt(a(".filo_overlay_container").css("border-top-width").split("px")[0]),i=parseInt(a(".picture_counter").height()),f=(d.maxWidth?d.maxWidth:a.filo.maxWidth)/100,d=(d.maxHeight?d.maxHeight:a.filo.maxHeight)/100,j=a(window).width()*f-g,h=a(window).height()*d-(g+i),k=new Image;k.onload=function(){var d=this.width,f=this.height,g,m;d>f?(g=d>j?j:d,m=g*f/d,m>h&&(m=f>h?h:f,g=m*d/f)):(m=f>h?h:f,g=m*d/f,g>j&&(g=d>j?j:d,m=g*f/d));0<a(".filo_overlay_container .filo_full_picture").length?
a(".filo_overlay_container .filo_full_picture").fadeOut(300,function(){a(k).css("display","none");k.width=g;k.height=m;a(".filo_overlay_container").width(g).height(m).css("margin-left",-1*(g/2)).css("margin-top",-1*(m/2)-i).prepend(k).find(k).fadeIn(300);a(this).remove();a(".filo_overlay_container_close").show();a(".filo_overlay_container .picture_counter").html("<span>Album: "+e+" | Pic: "+(parseInt(b)+1)+" of "+c.length+"</span>")}):(a(k).width(g).height(m),a(".filo_overlay_container").width(g).height(m).css("margin-left",
-1*(g/2)).css("margin-top",-1*(m/2)-i).prepend(k).fadeIn(300),a(".filo_overlay_container_close").show(),a(".filo_overlay_container .picture_counter").html("<span>Album: "+e+" | Pic: "+(parseInt(b)+1)+" of "+c.length+"</span>"));d=a(".filo_overlay_container .picture_counter span").width();a(".filo_overlay_container .picture_counter span").css("paddingLeft").split("px");f=a(".filo_overlay_container .picture_counter span").css("paddingRight").split("px")[0];a(".filo_overlay_container .picture_counter").width(d+
parseInt(f)+parseInt(f)).css("position","absolute").css("left","50%").css("marginLeft","-"+(d+parseInt(f)+parseInt(f))/2+"px")};k.setAttribute("class","filo_full_picture");k.setAttribute("id",b);k.src=c[b]}function u(a,b){if(0<a(".filo_overlay").length&&!a.filo.resize){a(".filo_full_picture").css("width","").css("height","");resize=!0;var c=(b.maxWidth?b.maxWidth:a.filo.maxWidth)/100,e=(b.maxHeight?b.maxHeight:a.filo.maxHeight)/100,d=parseInt(a(".filo_overlay_container").css("border-top-width").split("px")[0]),
g=parseInt(a(".picture_counter").height()),c=a(window).width()*c-d,e=a(window).height()*e-(d+g),d=parseInt(a(".filo_full_picture").width()),i=parseInt(a(".filo_full_picture").height()),f,j;d>i?(f=d>c?c:d,j=f*i/d,j>e&&(j=i>e?e:i,f=j*d/i)):(j=i>e?e:i,f=j*d/i,f>c&&(f=d>c?c:d,j=f*i/d));a(".filo_overlay_container img.filo_full_picture").width(f);a(".filo_overlay_container").width(f).height(j).css("margin-left",-1*(f/2)).css("margin-top",-1*(j/2)-g);resize=!1}}function w(a,b){for(var c=0;c<b.length;c++)if(a.toLowerCase()==
b[c].toLowerCase())return!0;return!1}c.fn.filo=function(a){if(c(this).length){void 0==a&&(a={container:this});-1==(void 0!=c(this).attr("class")&&c(this).attr("class").indexOf("template"))&&void 0!=a.template?c(this).addClass("template_"+a.template+" filo"):c(this).addClass("filo");var b=c(this).attr("id"),n=b+"_"+Date.now(),n=n.replace(".","");c(this).attr("id",n);s(c,n,b,a);c(window).unbind("resize");c(window).resize(function(){u(c,a)})}else console.log("filo container is undefined, please check the ID or class name")};
c.filo=function(a,b){void 0==b?b={container:"body"}:void 0==b.container&&(b.container="body");var n=a+"_"+Date.now(),n=n.replace(".",""),e=void 0!=b.template?"template_"+b.template:"";c(b.container).append('<div class="filo '+e+'" id="'+n+'"></div>');s(c,n,a,b);c(window).unbind("resize");c(window).resize(function(){u(c,b)})};jQuery.filo.getUrlParams=function(){for(var a=[],b,c=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),e=0;e<c.length;e++)b=c[e].split("="),a.push(b[0]),
a[b[0]]=b[1];return a};c(document).ready(function(){c.filo.toLoad=[];c.filo.isLoaded=[];c.filo.maxCountDefault=3;c.filo.overlayDefault="rgb(177,177,177)";c.filo.overlayOpacityDefault=0.5;c.filo.filo_loaderGraphicDefault="/img/bpx_loader.gif";c.filo.photos_array=null;c.filo.resize=!1;c.filo.closeButtons={black:"/img/close_black.png",white:"/img/close_white.png"};c.filo.defaultImage="/img/default.png";c.filo.order=["normal","reverse","random"];c.filo.method="post";c.filo.newWindow=!1;var a=c.filo,b;
a:{try{throw Error();}catch(n){var e="";void 0!=n.fileName?e=n.fileName.split("/"):(b=document.getElementsByTagName("script"),c.each(b,function(a,b){0<=b.src.indexOf("filo.js")&&(e=b.src.split("/"))}));if(""==e){b="filo/";break a}}b="";for(var d=0;d<e.length-1;d++)b=d<e.length-2?b+(e[d]+"/"):b+e[d]}a.root_path=b;c.filo.ie=!1;c.support.cors=!0;c.filo.maxHeight=90;c.filo.maxWidth=90;var g=[];c.each(c(".filo"),function(a,b){var e=c(b).attr("id"),d=e+"_"+Date.now()+"_"+Math.round(1E5*Math.random()),d=
d.replace(".","");c(b).attr("id",d);void 0!=c("#"+d).attr("maxCount")&&(g.maxCount=c("#"+d).attr("maxCount"));void 0!=c("#"+d).attr("href")&&(g.href=c("#"+d).attr("href"));void 0!=c("#"+d).attr("newWindow")&&(g.newWindow="true"==c("#"+d).attr("newWindow")?!0:!1);g.method=void 0!=c("#"+d).attr("method")?c("#"+d).attr("method"):"post";s(c,d,e,g);c(window).unbind("resize");c(window).resize(function(){u(c,g)})})});"undefined"==typeof c.browser&&(c.browser={msie:"Microsoft Internet Explorer"==navigator.appName});
Date.now=Date.now||function(){return+new Date}})(jQuery);
