/*
 * FILo <> Facebook Image Loader jQuery Plugin v1.0
 * http://www.berlinpix.com/filo
 *
 * Copyright 2012, BerlinPix.com
 * licensed under the LGPL license.
 *
 * Date: 2012-10-01
 */
var filo_jQuery=jQuery.noConflict();filo_jQuery.fn.filo=function(b){if(filo_jQuery(this).length){void 0==b&&(b={container:this});-1==(void 0!=filo_jQuery(this).attr("class")&&filo_jQuery(this).attr("class").indexOf("template"))&&void 0!=b.template?filo_jQuery(this).addClass("template_"+b.template+" filo"):filo_jQuery(this).addClass("filo");var a=filo_jQuery(this).attr("id"),f=a+"_"+Date.now(),f=f.replace(".","");filo_jQuery(this).attr("id",f);filoHandler(filo_jQuery,f,a,b)}else console.log("filo container is undefined, please check the ID or class name")};
filo_jQuery.filo=function(b,a){void 0==a?a={container:"body"}:void 0==a.container&&(a.container="body");var f=b+"_"+Date.now(),f=f.replace(".",""),c=void 0!=a.template?"template_"+a.template:"";filo_jQuery(a.container).append('<div class="filo '+c+'" id="'+f+'"></div>');filoHandler(filo_jQuery,f,b,a)};jQuery.filo.getUrlParams=function(){for(var b=[],a,f=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),c=0;c<f.length;c++)a=f[c].split("="),b.push(a[0]),b[a[0]]=a[1];return b};
function getUrlParams(){for(var b=[],a,f=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),c=0;c<f.length;c++)a=f[c].split("="),b.push(a[0]),b[a[0]]=a[1];return b}
filo_jQuery(document).ready(function(){filo_jQuery.filo.toLoad=[];filo_jQuery.filo.isLoaded=[];filo_jQuery.filo.maxCountDefault=3;filo_jQuery.filo.overlayDefault="rgb(177,177,177)";filo_jQuery.filo.overlayOpacityDefault=0.5;filo_jQuery.filo.filo_loaderGraphicDefault="/img/bpx_loader.gif";filo_jQuery.filo.photos_array=null;filo_jQuery.filo.resize=!1;filo_jQuery.filo.closeButtons={black:"/img/close_black.png",white:"/img/close_white.png"};filo_jQuery.filo.order=["normal","reverse","random"];filo_jQuery.filo.root_path=
getRootPath();filo_jQuery.filo.ie=!1;filo_jQuery.support.cors=!0;filo_jQuery.each(filo_jQuery(".filo"),function(b,a){var f=filo_jQuery(a).attr("id"),c=f+"_"+Date.now()+"_"+Math.round(1E5*Math.random()),c=c.replace(".","");filo_jQuery(a).attr("id",c);var d=[];void 0!=filo_jQuery("#"+c).attr("maxCount")&&(d.maxCount=filo_jQuery("#"+c).attr("maxCount"));void 0!=filo_jQuery("#"+c).attr("href")&&(d.href=filo_jQuery("#"+c).attr("href"));d.method=void 0!=filo_jQuery("#"+c).attr("method")?filo_jQuery("#"+
c).attr("method"):"post";filoHandler(filo_jQuery,c,f,d)});filo_jQuery(window).resize(function(){resizeImage(filo_jQuery)})});
function filoHandler(b,a,f,c){if("function"==typeof c.before){var d=jQuery.Event("FILo Before Event");c.before(d)}d=b.filo.root_path;d=void 0==c.filo_loaderGraphic?d+b.filo.filo_loaderGraphicDefault:c.filo_loaderGraphic;if(null==b(".filo_loader")||0==b(".filo_loader").length){var g=new Image;g.onload=function(){b(g).css("marginTop",-1*(this.height/2));b(g).css("marginLeft",-1*(this.width/2));b("#"+String(a)).append(g)};g.setAttribute("class","filo_loader");g.src=d}var i=[];b.each(b("#"+String(a)).find(".excluded"),
function(a,c){i.push(b(c).attr("id"))});var h=[];b.each(b("#"+a).find(".album"),function(a,c){h.push(b(c).attr("id"))});if(void 0!=c.albums&&0<c.albums.length)for(d=0;d<c.albums.length;d++)h.push(decodeURI(c.albums[d]));if(void 0!=c.excluded&&0<c.excluded.length)for(d=0;d<c.excluded.length;d++)i.push(decodeURI(c.excluded[d]));d="http://graph.facebook.com/"+f+"/albums";b.browser.msie?b.ajax({url:d,dataType:"jsonp"}).success(function(e){handleAlbum(b,a,f,e,h,i,c)}):b.getJSON(d,function(e){0>=e.data.length&&
(b(".filo_loader").remove(),alert("There are no albums, please check your Facebook-ID"));handleAlbum(b,a,f,e,h,i,c)}).error(function(){b(".filo_loader").remove();alert("Error while loading, please check your Facebook-ID")})}
function handleAlbum(b,a,f,c,d,g,i){b.filo.toLoad[a]=0;b.filo.isLoaded[a]=0;0<d.length?b.each(c.data,function(c,e){if(inArray(e.name,d)){b.filo.toLoad[a]+=1;var g=b.filo.maxCountDefault;void 0!=b("#"+a+" #"+e.name).attr("maxCount")?g=parseInt(b("#"+a+" #"+e.name).attr("maxCount")):void 0!=b("#"+a+" #"+e.name.toLowerCase()).attr("maxCount")?g=parseInt(b("#"+a+" #"+e.name.toLowerCase()).attr("maxCount")):void 0!=i&&void 0!=i.maxCount&&(g=i.maxCount);b("#"+a+" #"+e.name).remove();b("#"+a+" #"+e.name.toLowerCase()).remove();
var k=b('<div class="album" id="'+e.name+'"></div>').append('<div class="title">'+e.name+'</div><div class="thumbs"></div>');b(k).hide();b("#"+a).append(k);var j="all"==g?e.count:g;b.browser.msie?b.ajax({url:"http://graph.facebook.com/"+e.id+"/photos?limit="+j,dataType:"jsonp"}).success(function(c){handlePhoto(1,b,f,a,c,k,g,i)}):b.getJSON("http://graph.facebook.com/"+e.id+"/photos?limit="+j,function(c){handlePhoto(1,b,f,a,c,k,g,i)})}}):b.each(c.data,function(c,e){if(!inArray(e.name,g)){b.filo.toLoad[a]+=
1;var d=b.filo.maxCountDefault;void 0!=i&&void 0!=i.maxCount?d=i.maxCount:void 0!=b("#"+e.name).attr("maxCount")&&(d=parseInt(b("#"+e.name).attr("maxCount")));var k=b('<div class="album" id="'+e.name+'"></div>').append('<div class="title">'+e.name+'</div><div class="thumbs"></div>').hide();b("#"+a).append(k);b.browser.msie?b.ajax({url:"http://graph.facebook.com/"+e.id+"/photos?limit="+e.count,dataType:"jsonp"}).success(function(c){handlePhoto(1,b,f,a,c,k,d,i)}):b.getJSON("http://graph.facebook.com/"+
e.id+"/photos?limit="+e.count,function(c){handlePhoto(1,b,f,a,c,k,d,i)})}})}
function handlePhoto(b,a,f,c,d,g,i,h){var e=1==b?1:26*(b-1),m=[],b=d.data,k=a.filo.root_path;if(void 0!=h.order&&"reverse"==h.order)b.reverse();else if(void 0!=h.order&&"random"==h.order){for(var j=[],l=[];j.length<i&&j.length<b.length;){var n=Math.floor(Math.random()*b.length);void 0==l[n]&&(j.push(b[n]),l[n]=!0)}b=j}a.each(b,function(b,c){m[e-1]=c.source;var j=a('<div class="thumb thumb_'+e+(1==e?" first":"")+(e==i?" last":"")+'"><div class="inner"><a href="'+c.source+'"><img id="'+(e-1)+'" class="picture filo_picture" src="'+
c.picture+'"/></a></div></div>');a(j).find("img").load(function(){}).error(function(){console.log("loading image again");a(j).find("img").attr("src",a(j).attr("src"))});a(g).find(".thumbs").append(j);a(g).find(".filo_picture").click(function(b){b.preventDefault();if(void 0!=h.href)return"post"==h.method.toLowerCase()?(a("body").append('<form id="filo_forward" method="POST" action="'+h.href+'"><input name="profile" value="'+f+'" /><input name="album" value="'+a(g).attr("id")+'" /></form>'),a("#filo_forward").trigger("submit").remove()):
document.location=h.href+"?profile="+f+"&album="+a(g).attr("id"),!1;if(1>a(".filo_overlay").length){a.filo.closeButton=k+a.filo.closeButtons.black;void 0!=h.closeButton&&(a.filo.closeButton=void 0!=a.filo.closeButtons[h.closeButton]?k+a.filo.closeButtons[h.closeButton]:h.closeButton);var b=Math.max.apply(null,a.map(a("body > *"),function(b){return parseInt(a(b).css("z-index"))?parseInt(a(b).css("z-index")):1})),c=void 0!=h.overlay?"background: "+h.overlay+"; ":"background: "+a.filo.overlayDefault+
";",e=void 0!=h.overlayOpacity?" opacity: "+h.overlayOpacity+";":" opacity: "+a.filo.overlayOpacityDefault+";";a("body").append('<div class="filo_overlay" style="z-index:'+(b+1)+';" ><div class="filo_overlay_background" style="'+c+e+'"></div><div class="filo_overlay_container"><div class="filo_overlay_container_left"></div><div class="filo_overlay_container_right"></div><div class="picture_counter"></div></div></div>');var d=new Image;d.onload=function(){a(".filo_overlay_container").append(d);var b=
0<a(".filo_overlay_container").css("border-width")?a(".filo_overlay_container").css("border-width"):17;a(this).css("right",-1*(this.width/2+b));a(this).css("top",-1*(this.height/2+b));d.setAttribute("class","filo_overlay_container_close");a(".filo_overlay_container_close").click(function(){a(".filo_overlay").remove()})};d.src=a.filo.closeButton;setNewImage(a,a(this).attr("id"),m,a(g).attr("id"));a(".filo_overlay_background").click(function(b){"filo_overlay_background"==a(b.target).attr("class")&&
a(".filo_overlay").remove()});a(".filo_overlay_container_left").click(function(){var b=parseInt(a(".filo_full_picture").attr("id"));0<b&&setNewImage(a,b-1,m,a(g).attr("id"))});a(".filo_overlay_container_right").click(function(){var b=parseInt(a(".filo_full_picture").attr("id"));b<m.length-1&&setNewImage(a,b+1,m,a(g).attr("id"))});a(".filo_overlay_container_left").mouseenter(function(){a(this).css("backgroundColor","none").css("background-image","url('"+k+"/img/left_white.png')").css("background-repeat",
"no-repeat").css("background-position","left center")}).mouseout(function(){a(this).css("background-image","")});a(".filo_overlay_container_right").mouseenter(function(){a(this).css("backgroundColor","none").css("background-image","url('"+k+"/img/right_white.png')").css("background-repeat","no-repeat").css("background-position","right center")}).mouseout(function(){a(this).css("background-image","")})}});if(e>=i)return a(g).append('<div class="clear"></div>'),!1;e++;e==d.data.length&&a(g).append('<div class="clear"></div>')});
a.filo.isLoaded[c]+=1;a(g).fadeIn("slow");a.filo.isLoaded[c]==a.filo.toLoad[c]&&(a("#"+c+" .album").last().attr("class",a("#"+c+" .album").last().attr("class")+" last"),a("#"+c).append('<div class="clear"></div>'),a("#"+c+" .add").remove(),a("#"+c+" .excluded").remove(),a("#"+c+" .filo_loader").remove(),"function"==typeof h.load&&(c=jQuery.Event("FILo Load Event"),h.load(c)))}
function setNewImage(b,a,f,c){b(".filo_overlay_container_left").show();b(".filo_overlay_container_right").show();0==a&&b(".filo_overlay_container_left").hide();a==f.length-1&&b(".filo_overlay_container_right").hide();var d=parseInt(b(".filo_overlay_container").css("border-top-width").split("px")[0]),g=parseInt(b(".picture_counter").height()),i=0.9*b(window).width()-d,h=0.9*b(window).height()-(d+g),e=new Image;e.onload=function(){var d=this.width,k=this.height,j,l;d>k?(j=d>i?i:d,l=j*k/d,l>h&&(l=k>
h?h:k,j=l*d/k)):(l=k>h?h:k,j=l*d/k,j>i&&(j=d>i?i:d,l=j*k/d));0<b(".filo_overlay_container .filo_full_picture").length?b(".filo_overlay_container .filo_full_picture").fadeOut(300,function(){b(e).css("display","none");e.width=j;e.height=l;b(".filo_overlay_container").width(j).height(l).css("margin-left",-1*(j/2)).css("margin-top",-1*(l/2)-g).prepend(e).find(e).fadeIn(300);b(this).remove();b(".filo_overlay_container_close").show();b(".filo_overlay_container .picture_counter").html("<span>Album: "+c+
" | Pic: "+(parseInt(a)+1)+" of "+f.length+"</span>")}):(b(e).width(j).height(l),b(".filo_overlay_container").width(j).height(l).css("margin-left",-1*(j/2)).css("margin-top",-1*(l/2)-g).prepend(e).fadeIn(300),b(".filo_overlay_container_close").show(),b(".filo_overlay_container .picture_counter").html("<span>Album: "+c+" | Pic: "+(parseInt(a)+1)+" of "+f.length+"</span>"))};e.setAttribute("class","filo_full_picture");e.setAttribute("id",a);e.src=f[a]}
function resizeImage(b){if(0<b(".filo_overlay").length&&!b.filo.resize){b(".filo_full_picture").css("width","").css("height","");resize=!0;var a=parseInt(b(".filo_overlay_container").css("border-top-width").split("px")[0]),f=parseInt(b(".picture_counter").height()),c=0.9*b(window).width()-a,a=0.9*b(window).height()-(a+f),d=parseInt(b(".filo_full_picture").width()),g=parseInt(b(".filo_full_picture").height()),i,h;d>g?(i=d>c?c:d,h=i*g/d,h>a&&(h=g>a?a:g,i=h*d/g)):(h=g>a?a:g,i=h*d/g,i>c&&(i=d>c?c:d,h=
i*g/d));b(".filo_overlay_container img.filo_full_picture").width(i);b(".filo_overlay_container").width(i).height(h).css("margin-left",-1*(i/2)).css("margin-top",-1*(h/2)-f);resize=!1}}function inArray(b,a){for(var f=0;f<a.length;f++)if(b.toLowerCase()==a[f].toLowerCase())return!0;return!1}
function getRootPath(){try{throw Error();}catch(b){var a="";if(void 0!=b.fileName)a= b.fileName.split("/");else{var f=document.getElementsByTagName("script");filo_jQuery.each(f,function(b,c){0<=c.src.indexOf("filo.js")&&(a=c.src.split("/"))})}if(""==a)return"filo/"}for(var f="",c=0;c<a.length-1;c++)f=c<a.length-2?f+(a[c]+"/"):f+a[c];return f};
